-- PostgreSQL schema generated from the complete D1 schema (worker/schema.sql).
-- The column names and data contracts are intentionally preserved.
BEGIN;

CREATE TABLE IF NOT EXISTS users (

  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username TEXT UNIQUE NOT NULL,
  password_hash TEXT NOT NULL,
  salt TEXT NOT NULL,
  nombre TEXT NOT NULL,
  rol TEXT NOT NULL DEFAULT 'redactor', -- 'admin', 'redactor' o 'fotografo' (colaborador; ver migracion_colaboradores_fotografo.sql)
  activo INTEGER NOT NULL DEFAULT 1,
  -- Correo electrónico del usuario. Se pide obligatoriamente la primera vez
  -- que inicia sesión (queda NULL hasta entonces) y sirve para poder
  -- recuperar la contraseña desde "He olvidado mi contraseña".
  email TEXT,
  -- Perfil público del redactor/admin (se muestra en su página de autor,
  -- enlazada desde el nombre en sus noticias): biografía corta, experiencia
  -- previa, foto y redes sociales propias (JSON con las mismas claves que
  -- las redes del medio: twitter/instagram/tiktok/youtube), todo opcional
  -- y editable por cada persona desde "Ajustes de cuenta" en el panel.
  bio TEXT,
  experiencia TEXT,
  avatar_url TEXT,
  redes_sociales TEXT,
  -- Equipo(s) de futbol que sigue o cubre habitualmente el redactor o
  -- admin: hasta 3 clubes de public/js/clubs.js, guardados como un
  -- array JSON en texto (p. ej. '["Real Madrid","FC Barcelona"]').
  -- Se muestra en su perfil publico y en el desplegable de autor al
  -- firmar una noticia. Solo lo puede asignar o cambiar un admin desde
  -- "Usuarios"; la propia persona lo ve en "Mis datos" pero no puede
  -- editarlo ahi. Opcional (puede no tener ninguno asignado).
  equipo TEXT,
  -- Última vez que la persona ha visto las novedades (campana de
  -- notificaciones) del panel, guardado en el servidor para que no se
  -- pierda si se borran las cookies/datos del navegador.
  notif_visto_at TEXT,
  -- Recuperación de contraseña por email: token de un solo uso (caduca
  -- a los 30 minutos) generado al pedir "He olvidado mi contraseña".
  -- Se borra (vuelve a NULL) en cuanto se usa o al caducar.
  reset_token TEXT,
  reset_token_expira TEXT,
  created_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP)
);

CREATE TABLE IF NOT EXISTS articles (

  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  slug TEXT UNIQUE NOT NULL,
  titulo TEXT NOT NULL,
  subtitulo TEXT,
  contenido TEXT NOT NULL,
  tipo TEXT NOT NULL DEFAULT 'noticia', -- noticia, cronica, opinion, entrevista
  categoria TEXT NOT NULL DEFAULT 'hypermotion', -- hypermotion, primera_federacion, segunda_federacion, general
  club TEXT,
  imagen_url TEXT,
  -- Fotos adicionales de la noticia/crónica, guardadas como un array JSON
  -- de URLs (p.ej. '["https://...1.jpg","https://...2.jpg"]'). La primera
  -- imagen del array coincide siempre con "imagen_url" (la portada), que
  -- se mantiene por compatibilidad con las tarjetas y la portada.
  imagenes TEXT,
  -- Partido al que hace referencia la noticia/crónica (opcional). Permite
  -- que, una vez finalizado un partido en "Resultados", se enlace su
  -- marcador dentro de la noticia/crónica que se escriba sobre él.
  resultado_id INTEGER,
  autor_id INTEGER,
  autor_nombre TEXT,
  -- Segundo autor opcional (noticia firmada por dos personas). Solo un
  -- nombre extra que se muestra junto al autor principal; el autor
  -- principal (autor_id/autor_nombre) sigue siendo el que manda a
  -- efectos de permisos de edición, autor.html y SEO.
  coautor_id INTEGER,
  coautor_nombre TEXT,
  destacado INTEGER NOT NULL DEFAULT 0,
  publicado INTEGER NOT NULL DEFAULT 1,
  -- Cuando la noticia se guarda como borrador (publicado = 0), indica en
  -- qué punto está: 'terminado' (el redactor considera que ya está lista
  -- para que alguien la revise/publique, así que se avisa por email a la
  -- redacción) o 'en_proceso' (todavía la está escribiendo, así que no se
  -- manda ningún correo para no generar avisos de más). Se pregunta con
  -- una notificación en el panel justo al guardar como borrador. NULL
  -- cuando el artículo está publicado (no aplica).
  estado_borrador TEXT,
  -- Fecha/hora (UTC, formato ISO) en la que un administrador ha programado
  -- que esta noticia se publique sola, sin tener que entrar al panel a esa
  -- hora. Mientras esté rellena y en el futuro, la noticia se guarda con
  -- publicado = 0 (no visible en la web); el disparador programado del
  -- Worker (ver "scheduled" en src/index.js) revisa cada minuto si ya ha
  -- llegado esa hora y, si es así, la publica y limpia esta columna. NULL
  -- cuando la noticia no está programada (se ha publicado directamente, se
  -- ha guardado como borrador normal, o ya se ha publicado la programada).
  programado_para TEXT,
  -- Se pone a 1 en cuanto la noticia se publica por primera vez (a mano o
  -- porque el disparador programado la publica sola). Mientras esté a 0
  -- (borrador o programada, nunca publicada todavía), el slug se
  -- recalcula a partir del título cada vez que se guarda; en cuanto pasa
  -- a 1, el slug queda fijo para siempre y no vuelve a cambiar aunque se
  -- edite el título después (para no romper enlaces ya compartidos). Ver
  -- también la tabla article_slug_redirects más abajo.
  slug_congelado INTEGER NOT NULL DEFAULT 0,
  fecha_publicacion TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP),
  created_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP),
  updated_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP),
  -- Traducciones opcionales del artículo (solo contenido, no interfaz).
  -- Si el redactor no traduce a un idioma, estos campos quedan NULL y esa
  -- noticia se sigue viendo en castellano ahí, avisando de que no está
  -- disponible en ese idioma.
  titulo_eu TEXT, subtitulo_eu TEXT, contenido_eu TEXT,
  titulo_ca TEXT, subtitulo_ca TEXT, contenido_ca TEXT,
  titulo_gl TEXT, subtitulo_gl TEXT, contenido_gl TEXT,
  titulo_en TEXT, subtitulo_en TEXT, contenido_en TEXT,
  -- Columna heredada del antiguo sistema de imagen para redes (ya
  -- retirado); se mantiene sin usar para no forzar una migración
  -- destructiva sobre datos existentes.
  imagen_post_url TEXT
);

CREATE TABLE IF NOT EXISTS results (

  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  competicion TEXT NOT NULL, -- hypermotion, primera_federacion, segunda_federacion
  grupo TEXT, -- para Segunda Federación (Grupo 1, Grupo 2...)
  jornada INTEGER NOT NULL,
  equipo_local TEXT NOT NULL,
  equipo_visitante TEXT NOT NULL,
  goles_local INTEGER,
  goles_visitante INTEGER,
  fecha_partido TEXT, -- fecha y, si se conoce, hora del partido ("YYYY-MM-DD" o "YYYY-MM-DDTHH:MM")
  estado TEXT NOT NULL DEFAULT 'programado', -- programado, en_juego, finalizado
  -- Dónde se juega el partido (estadio, ciudad...). Se muestra junto a la
  -- fecha/hora en los partidos que todavía no se han disputado ("Por
  -- jugar"), tanto en la portada como en Resultados.
  ubicacion TEXT,
  -- Enlace a la ficha del partido en Flashscore. Solo tiene sentido (y
  -- solo se muestra en el frontend) para partidos ya finalizados de
  -- Primera Federación, Segunda Federación y LaLiga Hypermotion/LaLiga2.
  flashscore_url TEXT,
  -- Escudo personalizado (subido a Cloudinary) para un equipo "externo"
  -- que no está en la lista de public/js/clubs.js. Si están vacíos, el
  -- frontend resuelve el escudo automáticamente a partir del nombre del
  -- equipo (ver getEscudoUrl en clubs.js).
  escudo_local_url TEXT,
  escudo_visitante_url TEXT,
  -- Quién creó/gestiona este resultado. Igual que en articles, permite
  -- restringir su edición: cada redactor solo edita los suyos salvo que
  -- se le apruebe una solicitud de edición (ver tabla edit_requests).
  autor_id INTEGER,
  autor_nombre TEXT,
  created_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP),
  -- Instante (UTC) en que se pulsó "Iniciar partido" en el panel de
  -- Minuto a Minuto; sirve para calcular el cronómetro en vivo. NULL si
  -- el partido nunca se ha iniciado desde el panel.
  inicio_cronometro_at TEXT,
  -- Minuto en el que se congeló el cronómetro (al pulsar "Descanso",
  -- "Pausa de hidratación" o "Fin del partido" en el panel). NULL
  -- mientras corre con normalidad.
  cronometro_pausado_en INTEGER,
  -- Desplazamiento manual (minutos, puede ser negativo) que se suma al
  -- cronómetro calculado a partir de inicio_cronometro_at. Se usa para
  -- "Editar minuto" en el panel y para arrancar el cronómetro ya
  -- avanzado (p.ej. si el redactor marca "En juego" a mano 15 minutos
  -- después de la hora programada). 0 = sin ajuste.
  ajuste_cronometro_minutos INTEGER NOT NULL DEFAULT 0,
  -- Nueva fecha/hora cuando se marca el partido como "retrasado" (se
  -- guarda aparte de fecha_partido para conservar el horario original).
  fecha_partido_retrasado TEXT,
  -- Goles marcados en la tanda de penaltis (partidos eliminatorios
  -- empatados al final de la prórroga/tiempo reglamentario). NULL en
  -- los dos = no hubo tanda; el resultado del tiempo reglamentario
  -- sigue en goles_local/goles_visitante sin tocar. Se recalculan solos
  -- a partir de los eventos "penalti_marcado"/"penalti_fallado_tanda",
  -- igual que el marcador normal (ver recalcularPenaltisDesdeEventos).
  penaltis_local INTEGER,
  penaltis_visitante INTEGER,
  -- Evita repetir el email de "partido desatendido" (ver
  -- revisarPartidosDesatendidos) cada minuto mientras nadie lo
  -- soluciona: guarda qué mitades del partido ya han mandado su aviso
  -- ("primera", "segunda" o "primera_segunda"), como máximo un aviso
  -- por mitad en vez de un único aviso para todo el partido.
  aviso_desatendido_mitad TEXT,
  -- MVP (jugador destacado) del partido, elegido por un redactor desde
  -- el panel de Minuto a Minuto o el panel normal de edición. Texto
  -- libre (mismo formato que "jugador" en match_events: dorsal, nombre
  -- o ambos) + de qué equipo es, para poder pintar su escudo. NULL en
  -- los dos si todavía no se ha elegido.
  mvp_jugador TEXT,
  mvp_equipo TEXT -- 'local' | 'visitante'
);

CREATE TABLE IF NOT EXISTS match_events (

  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  resultado_id INTEGER NOT NULL REFERENCES results(id) ON DELETE CASCADE,
  tipo TEXT NOT NULL, -- gol, gol_var, gol_pp, amarilla, doble_amarilla, roja, cambio, inicio_partido, descanso, fin_descanso, pausa_hidratacion, fin_pausa_hidratacion, fin_partido, var, penalti_fallado, penalti_marcado, penalti_fallado_tanda, partido_retrasado, partido_anulado, otro
  equipo TEXT NOT NULL, -- 'local' o 'visitante' (o 'ninguno' para eventos sin equipo, como descanso). En "gol_pp" es el equipo del jugador que marca en su propia puerta (el gol cuenta para el rival). En "penalti_marcado"/"penalti_fallado_tanda" es el equipo que tira.
  jugador TEXT,
  jugador_sale TEXT, -- solo para tipo "cambio": jugador que sale (en "jugador" se guarda el que entra)
  jugador_asistencia TEXT, -- solo para tipo "gol": jugador que da la asistencia (opcional)
  minuto INTEGER NOT NULL, -- en "penalti_marcado"/"penalti_fallado_tanda" es el número de orden en la tanda (1, 2, 3...), no un minuto real
  minuto_extra INTEGER, -- minutos de descuento (ej. 45+2 -> minuto=45, minuto_extra=2)
  orden INTEGER NOT NULL DEFAULT 0, -- para desempatar eventos en el mismo minuto
  bajar_gol INTEGER NOT NULL DEFAULT 0, -- solo para tipo "gol_var": si 1, este gol anulado ya se había sumado al marcador y hay que restarlo; si 0, se registra sin tocar el marcador
  created_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP)
);

CREATE TABLE IF NOT EXISTS settings (

  key TEXT PRIMARY KEY,
  value TEXT NOT NULL,
  updated_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP)
);

CREATE TABLE IF NOT EXISTS media (

  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  cloudinary_public_id TEXT UNIQUE NOT NULL,
  cloudinary_resource_type TEXT NOT NULL, -- 'image' o 'video' (lo exige la API de Cloudinary para borrar)
  cloudinary_url TEXT NOT NULL,
  titulo TEXT NOT NULL,
  descripcion TEXT,
  tipo TEXT NOT NULL, -- 'foto' o 'video'
  nombre_archivo TEXT NOT NULL,
  content_type TEXT NOT NULL,
  tamano_bytes INTEGER NOT NULL,
  autor_id INTEGER,
  autor_nombre TEXT,
  club TEXT,
  created_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP)
);

CREATE TABLE IF NOT EXISTS sessions (

  id TEXT PRIMARY KEY,
  user_id INTEGER NOT NULL,
  user_agent TEXT,
  ip TEXT,
  created_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP),
  last_seen_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP),
  revoked_at TEXT
);

CREATE TABLE IF NOT EXISTS custom_clubs (

  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre TEXT NOT NULL,
  categoria TEXT NOT NULL,
  escudo_url TEXT,
  autor_id INTEGER,
  autor_nombre TEXT,
  created_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP),
  UNIQUE (nombre, categoria)
);

CREATE TABLE IF NOT EXISTS edit_requests (

  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tipo_entidad TEXT NOT NULL, -- 'articulo' o 'resultado'
  entidad_id INTEGER NOT NULL,
  solicitante_id INTEGER NOT NULL,
  autor_id INTEGER,
  motivo TEXT,
  estado TEXT NOT NULL DEFAULT 'pendiente', -- pendiente, aprobada, rechazada, caducada
  resuelta_por_id INTEGER,
  resuelta_at TEXT,
  permiso_expira_at TEXT,
  created_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP)
);

CREATE TABLE IF NOT EXISTS article_slug_redirects (

  slug_antiguo TEXT PRIMARY KEY,
  article_id INTEGER NOT NULL REFERENCES articles(id) ON DELETE CASCADE,
  created_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP)
);

CREATE TABLE IF NOT EXISTS alineaciones (

  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  article_id INTEGER,
  result_id INTEGER,
  equipo TEXT NOT NULL,
  escudo_url TEXT,
  formacion TEXT NOT NULL DEFAULT '4-3-3',
  jugadores TEXT NOT NULL DEFAULT '[]',
  autor_id INTEGER,
  autor_nombre TEXT,
  created_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP),
  updated_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP)
);

CREATE TABLE IF NOT EXISTS comments (

  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  article_id INTEGER NOT NULL REFERENCES articles(id) ON DELETE CASCADE,
  nombre TEXT NOT NULL,
  email TEXT NOT NULL,
  texto TEXT NOT NULL,
  estado TEXT NOT NULL DEFAULT 'pendiente',
  ip TEXT,
  created_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP),
  moderado_por_id INTEGER,
  moderado_at TEXT
);

CREATE TABLE IF NOT EXISTS club_info (

  club TEXT PRIMARY KEY,
  entrenador TEXT,
  estadio TEXT,
  fundacion INTEGER,
  ciudad TEXT,
  autor_id INTEGER,
  autor_nombre TEXT,
  created_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP),
  updated_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP)
);

CREATE TABLE IF NOT EXISTS club_info_solicitudes (

  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  club TEXT NOT NULL,
  entrenador TEXT,
  estadio TEXT,
  fundacion INTEGER,
  ciudad TEXT,
  solicitante_id INTEGER NOT NULL,
  solicitante_nombre TEXT,
  estado TEXT NOT NULL DEFAULT 'pendiente',
  resuelta_por_id INTEGER,
  resuelta_por_nombre TEXT,
  resuelta_at TEXT,
  created_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP)
);

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'articles_autor_id_fk') THEN
    ALTER TABLE articles ADD CONSTRAINT articles_autor_id_fk FOREIGN KEY (autor_id) REFERENCES users (id);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'articles_coautor_id_fk') THEN
    ALTER TABLE articles ADD CONSTRAINT articles_coautor_id_fk FOREIGN KEY (coautor_id) REFERENCES users (id);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'articles_resultado_id_fk') THEN
    ALTER TABLE articles ADD CONSTRAINT articles_resultado_id_fk FOREIGN KEY (resultado_id) REFERENCES results (id);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'results_autor_id_fk') THEN
    ALTER TABLE results ADD CONSTRAINT results_autor_id_fk FOREIGN KEY (autor_id) REFERENCES users (id);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'media_autor_id_fk') THEN
    ALTER TABLE media ADD CONSTRAINT media_autor_id_fk FOREIGN KEY (autor_id) REFERENCES users (id);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'sessions_user_id_fk') THEN
    ALTER TABLE sessions ADD CONSTRAINT sessions_user_id_fk FOREIGN KEY (user_id) REFERENCES users (id);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'custom_clubs_autor_id_fk') THEN
    ALTER TABLE custom_clubs ADD CONSTRAINT custom_clubs_autor_id_fk FOREIGN KEY (autor_id) REFERENCES users (id);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'edit_requests_solicitante_id_fk') THEN
    ALTER TABLE edit_requests ADD CONSTRAINT edit_requests_solicitante_id_fk FOREIGN KEY (solicitante_id) REFERENCES users (id);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'edit_requests_autor_id_fk') THEN
    ALTER TABLE edit_requests ADD CONSTRAINT edit_requests_autor_id_fk FOREIGN KEY (autor_id) REFERENCES users (id);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'edit_requests_resuelta_por_id_fk') THEN
    ALTER TABLE edit_requests ADD CONSTRAINT edit_requests_resuelta_por_id_fk FOREIGN KEY (resuelta_por_id) REFERENCES users (id);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'alineaciones_article_id_fk') THEN
    ALTER TABLE alineaciones ADD CONSTRAINT alineaciones_article_id_fk FOREIGN KEY (article_id) REFERENCES articles (id) ON DELETE CASCADE;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'alineaciones_result_id_fk') THEN
    ALTER TABLE alineaciones ADD CONSTRAINT alineaciones_result_id_fk FOREIGN KEY (result_id) REFERENCES results (id) ON DELETE CASCADE;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'alineaciones_autor_id_fk') THEN
    ALTER TABLE alineaciones ADD CONSTRAINT alineaciones_autor_id_fk FOREIGN KEY (autor_id) REFERENCES users (id);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'comments_moderado_por_id_fk') THEN
    ALTER TABLE comments ADD CONSTRAINT comments_moderado_por_id_fk FOREIGN KEY (moderado_por_id) REFERENCES users (id);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'club_info_autor_id_fk') THEN
    ALTER TABLE club_info ADD CONSTRAINT club_info_autor_id_fk FOREIGN KEY (autor_id) REFERENCES users (id);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'club_info_solicitudes_solicitante_id_fk') THEN
    ALTER TABLE club_info_solicitudes ADD CONSTRAINT club_info_solicitudes_solicitante_id_fk FOREIGN KEY (solicitante_id) REFERENCES users (id);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'club_info_solicitudes_resuelta_por_id_fk') THEN
    ALTER TABLE club_info_solicitudes ADD CONSTRAINT club_info_solicitudes_resuelta_por_id_fk FOREIGN KEY (resuelta_por_id) REFERENCES users (id);
  END IF;
END $$;

CREATE INDEX IF NOT EXISTS idx_match_events_resultado ON match_events(resultado_id);
CREATE INDEX IF NOT EXISTS idx_media_created ON media(created_at);
CREATE INDEX IF NOT EXISTS idx_sessions_user ON sessions(user_id);
CREATE INDEX IF NOT EXISTS idx_articles_categoria ON articles(categoria);
CREATE INDEX IF NOT EXISTS idx_articles_publicado ON articles(publicado, fecha_publicacion);
CREATE INDEX IF NOT EXISTS idx_results_competicion ON results(competicion, jornada);
CREATE INDEX IF NOT EXISTS idx_custom_clubs_categoria ON custom_clubs(categoria);
CREATE INDEX IF NOT EXISTS idx_edit_requests_entidad ON edit_requests(tipo_entidad, entidad_id);
CREATE INDEX IF NOT EXISTS idx_edit_requests_solicitante ON edit_requests(solicitante_id, estado);
CREATE INDEX IF NOT EXISTS idx_edit_requests_estado ON edit_requests(estado);
CREATE INDEX IF NOT EXISTS idx_alineaciones_article ON alineaciones(article_id);
CREATE INDEX IF NOT EXISTS idx_alineaciones_result ON alineaciones(result_id);
CREATE INDEX IF NOT EXISTS idx_comments_article ON comments(article_id, estado);
CREATE INDEX IF NOT EXISTS idx_comments_estado ON comments(estado, created_at);
CREATE INDEX IF NOT EXISTS idx_club_info_solicitudes_estado ON club_info_solicitudes(estado);
CREATE INDEX IF NOT EXISTS idx_club_info_solicitudes_club ON club_info_solicitudes(club);


ALTER TABLE users ADD COLUMN IF NOT EXISTS nivel INTEGER NOT NULL DEFAULT 1;
ALTER TABLE users ADD COLUMN IF NOT EXISTS nivel_nota TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS ultima_hora_hash TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS ultima_hora_salt TEXT;
ALTER TABLE results ADD COLUMN IF NOT EXISTS aviso_desatendido_enviado INTEGER NOT NULL DEFAULT 0;

CREATE TABLE IF NOT EXISTS activity_log (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  usuario_id INTEGER,
  usuario_nombre TEXT NOT NULL,
  usuario_rol TEXT NOT NULL,
  accion TEXT NOT NULL,
  entidad TEXT,
  entidad_id TEXT,
  descripcion TEXT NOT NULL,
  detalle TEXT,
  ip TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_activity_created ON activity_log(created_at);
CREATE INDEX IF NOT EXISTS idx_activity_usuario ON activity_log(usuario_id);
CREATE INDEX IF NOT EXISTS idx_activity_accion ON activity_log(accion);
CREATE INDEX IF NOT EXISTS idx_activity_entidad ON activity_log(entidad, entidad_id);

CREATE TABLE IF NOT EXISTS nivel_historial (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  usuario_id INTEGER NOT NULL,
  usuario_nombre TEXT NOT NULL,
  nivel_anterior INTEGER NOT NULL,
  nivel_nuevo INTEGER NOT NULL,
  motivo TEXT,
  cambiado_por_id INTEGER,
  cambiado_por_nombre TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_nivel_historial_usuario ON nivel_historial(usuario_id);

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'activity_log_usuario_fk') THEN
    ALTER TABLE activity_log ADD CONSTRAINT activity_log_usuario_fk FOREIGN KEY (usuario_id) REFERENCES users(id);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'nivel_historial_usuario_fk') THEN
    ALTER TABLE nivel_historial ADD CONSTRAINT nivel_historial_usuario_fk FOREIGN KEY (usuario_id) REFERENCES users(id);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'nivel_historial_cambiado_por_fk') THEN
    ALTER TABLE nivel_historial ADD CONSTRAINT nivel_historial_cambiado_por_fk FOREIGN KEY (cambiado_por_id) REFERENCES users(id);
  END IF;
END $$;

COMMIT;
