-- Migración 027: tabla match_gallery (mismo esquema que
-- worker/migracion_match_gallery.sql en D1; ver ese fichero para el
-- contexto completo y el porqué del diseño como tabla puente en vez
-- de una columna "partido_id" en "media").
--
-- IMPORTANTE: SÍ añadir esta tabla a sync/tables.mjs (a diferencia de
-- avisos_desatendidos_cola en la migración 026): la galería de
-- partido la sube el fotógrafo desde el Worker principal (D1) y tiene
-- que llegar también a PostgreSQL para que el failover a Railway siga
-- sirviendo la misma galería. Ya está registrada ahí con
-- order: 5.5, justo después de "media".
BEGIN;

CREATE TABLE IF NOT EXISTS match_gallery (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  result_id INTEGER NOT NULL,
  media_id INTEGER NOT NULL,
  orden INTEGER NOT NULL DEFAULT 0,
  vinculado_por_id INTEGER,
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE match_gallery ADD CONSTRAINT match_gallery_result_id_fk
  FOREIGN KEY (result_id) REFERENCES results (id) ON DELETE CASCADE;
ALTER TABLE match_gallery ADD CONSTRAINT match_gallery_media_id_fk
  FOREIGN KEY (media_id) REFERENCES media (id) ON DELETE CASCADE;
ALTER TABLE match_gallery ADD CONSTRAINT match_gallery_vinculado_por_id_fk
  FOREIGN KEY (vinculado_por_id) REFERENCES users (id);

CREATE UNIQUE INDEX IF NOT EXISTS idx_match_gallery_unico
  ON match_gallery(result_id, media_id);
CREATE INDEX IF NOT EXISTS idx_match_gallery_result
  ON match_gallery(result_id, orden);
CREATE INDEX IF NOT EXISTS idx_match_gallery_media
  ON match_gallery(media_id);

COMMIT;
