-- Migración 031: noticias rápidas (foto + titular + subtitular).
--
-- Mismo esquema que worker/migracion_noticias_rapidas.sql en D1, aplicado
-- aquí a Postgres para que el esquema de ambas bases coincida (si no, el
-- failover a Railway fallaría con `relation "noticias_rapidas" does not
-- exist`, como ya pasó con "polls", ver 012_encuestas.sql).

BEGIN;

CREATE TABLE IF NOT EXISTS noticias_rapidas (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  titulo TEXT NOT NULL,
  subtitulo TEXT NOT NULL,
  imagen_url TEXT NOT NULL,
  autor_id INTEGER REFERENCES users(id),
  created_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP),
  updated_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP)
);
CREATE INDEX IF NOT EXISTS idx_noticias_rapidas_created ON noticias_rapidas(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_noticias_rapidas_autor ON noticias_rapidas(autor_id);

COMMIT;
