-- Migracion 036: notificaciones push (push_subscriptions).
-- Mismo esquema que worker/migracion_push.sql en D1, aplicado aqui a
-- Postgres para que ambas bases coincidan y el failover a Railway tambien
-- pueda registrar suscripciones y enviar avisos.
BEGIN;

CREATE TABLE IF NOT EXISTS push_subscriptions (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  endpoint TEXT NOT NULL UNIQUE,
  p256dh TEXT NOT NULL,
  auth TEXT NOT NULL,
  noticias INTEGER NOT NULL DEFAULT 1,
  partidos INTEGER NOT NULL DEFAULT 1,
  user_agent TEXT,
  created_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP),
  updated_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP)
);
CREATE INDEX IF NOT EXISTS idx_push_noticias ON push_subscriptions(noticias);
CREATE INDEX IF NOT EXISTS idx_push_partidos ON push_subscriptions(partidos);

COMMIT;
