-- Migración 039: votaciones internas (panel de redacción).
-- Mismo esquema FINAL que en D1, es decir, el resultado de aplicar en orden:
--   worker/migracion_votaciones_internas.sql
--   worker/migracion_votaciones_obligatorias.sql  (columna "obligatoria")
--   worker/migracion_votaciones_privadas.sql      (participacion + urna)
--
-- PRIVACIDAD (no tocar sin leer migracion_votaciones_privadas.sql de D1):
-- en votaciones anónimas el voto vive en votaciones_internas_urna SIN
-- usuario y SIN fecha, y la participación en
-- votaciones_internas_participacion SIN opción. Aquí se replican las dos
-- tablas tal cual; no se debe añadir ninguna columna que las vuelva a unir.
--
-- Estas 5 tablas SÍ se sincronizan D1 -> PostgreSQL (ver sync/tables.mjs,
-- Fase 2 de la sincronización completa): la API secundaria las lee/escribe
-- cuando atiende el failover.
BEGIN;

CREATE TABLE IF NOT EXISTS votaciones_internas (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  titulo TEXT NOT NULL,
  descripcion TEXT,
  multiple INTEGER NOT NULL DEFAULT 0,
  anonima INTEGER NOT NULL DEFAULT 0,
  obligatoria INTEGER NOT NULL DEFAULT 0,
  resultados_visibles TEXT NOT NULL DEFAULT 'tras_votar',
  cierra_en TEXT,
  estado TEXT NOT NULL DEFAULT 'abierta',
  creado_por INTEGER REFERENCES users(id),
  creado_por_nombre TEXT,
  created_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP),
  cerrada_en TEXT
);
-- Por si la tabla ya existía sin la columna (despliegues parciales).
ALTER TABLE votaciones_internas ADD COLUMN IF NOT EXISTS obligatoria INTEGER NOT NULL DEFAULT 0;

CREATE TABLE IF NOT EXISTS votaciones_internas_opciones (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  votacion_id INTEGER NOT NULL REFERENCES votaciones_internas(id) ON DELETE CASCADE,
  texto TEXT NOT NULL,
  orden INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS votaciones_internas_votos (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  votacion_id INTEGER NOT NULL REFERENCES votaciones_internas(id) ON DELETE CASCADE,
  opcion_id INTEGER NOT NULL REFERENCES votaciones_internas_opciones(id) ON DELETE CASCADE,
  usuario_id INTEGER NOT NULL REFERENCES users(id),
  created_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP),
  UNIQUE (opcion_id, usuario_id)
);

CREATE TABLE IF NOT EXISTS votaciones_internas_participacion (
  votacion_id INTEGER NOT NULL REFERENCES votaciones_internas(id) ON DELETE CASCADE,
  usuario_id INTEGER NOT NULL REFERENCES users(id),
  PRIMARY KEY (votacion_id, usuario_id)
);

CREATE TABLE IF NOT EXISTS votaciones_internas_urna (
  token TEXT PRIMARY KEY,
  votacion_id INTEGER NOT NULL REFERENCES votaciones_internas(id) ON DELETE CASCADE,
  opcion_id INTEGER NOT NULL REFERENCES votaciones_internas_opciones(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_votint_opciones_votacion ON votaciones_internas_opciones(votacion_id);
CREATE INDEX IF NOT EXISTS idx_votint_votos_votacion ON votaciones_internas_votos(votacion_id);
CREATE INDEX IF NOT EXISTS idx_votint_votos_usuario ON votaciones_internas_votos(usuario_id, votacion_id);
CREATE INDEX IF NOT EXISTS idx_votint_urna_votacion ON votaciones_internas_urna(votacion_id, opcion_id);

COMMIT;
