-- Migración 042: article_media (galería/imágenes de una noticia, Fase 12).
-- Mismo esquema que worker/migracion_article_media.sql en D1. Sin esta tabla,
-- GET /api/articles/:slug falla en la secundaria para CUALQUIER noticia.
BEGIN;

CREATE TABLE IF NOT EXISTS article_media (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  article_id INTEGER NOT NULL REFERENCES articles(id) ON DELETE CASCADE,
  media_id INTEGER NOT NULL REFERENCES media(id) ON DELETE CASCADE,
  orden INTEGER NOT NULL DEFAULT 0,
  created_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP)
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_article_media_unico ON article_media(article_id, media_id);
CREATE INDEX IF NOT EXISTS idx_article_media_article ON article_media(article_id, orden);
CREATE INDEX IF NOT EXISTS idx_article_media_media ON article_media(media_id);

COMMIT;
