-- Migración 049: solicitudes de acreditación (formulario público).
-- Mismo esquema que worker/migracion_acreditaciones.sql en D1, para que el
-- failover a Railway no falle con `relation "acreditaciones" does not exist`
-- (ver 031_noticias_rapidas.sql).

BEGIN;

CREATE TABLE IF NOT EXISTS acreditaciones (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre TEXT NOT NULL,
  email TEXT NOT NULL,
  dni TEXT NOT NULL,
  equipo TEXT NOT NULL,
  tipo_evento TEXT NOT NULL,
  tipo_acreditacion TEXT NOT NULL,
  funciones TEXT NOT NULL,
  jornada_partido TEXT NOT NULL,
  confirmado INTEGER NOT NULL DEFAULT 1,
  estado TEXT NOT NULL DEFAULT 'pendiente',
  nota_admin TEXT,
  revisado_por TEXT,
  revisado_at TEXT,
  created_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP),
  updated_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP)
);
CREATE INDEX IF NOT EXISTS idx_acreditaciones_created ON acreditaciones(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_acreditaciones_estado ON acreditaciones(estado);

COMMIT;
