-- Migración 050: anuncios por correo desde el panel de admin (Funcionalidades > Anuncios).
-- Mismo esquema que worker/migracion_anuncios_email.sql en D1, para que el
-- failover a Railway no falle con `relation "anuncios_email" does not exist`.
-- La columna "audiencias" guarda JSON: lista antigua ["admins","lectores"] o
-- selección por personas {"admins":"todos","redactores":["ana@x.com"]}.

BEGIN;

CREATE TABLE IF NOT EXISTS anuncios_email (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  asunto TEXT NOT NULL,
  mensaje TEXT NOT NULL,
  audiencias TEXT NOT NULL,
  boton_texto TEXT,
  boton_url TEXT,
  creado_por_id INTEGER,
  creado_por_nombre TEXT,
  total_destinatarios INTEGER NOT NULL DEFAULT 0,
  enviados INTEGER NOT NULL DEFAULT 0,
  fallidos INTEGER NOT NULL DEFAULT 0,
  estado TEXT NOT NULL DEFAULT 'enviando',
  created_at TEXT NOT NULL DEFAULT (to_char(timezone('utc', now()), 'YYYY-MM-DD HH24:MI:SS')),
  completado_at TEXT
);
CREATE INDEX IF NOT EXISTS idx_anuncios_email_created ON anuncios_email(created_at);

COMMIT;
