-- Migración 051: formularios personalizados (constructor de formularios).
-- Mismo esquema que worker/migracion_formularios.sql en D1, para que el
-- failover a Railway no falle con `relation "formularios" does not exist`.

BEGIN;

CREATE TABLE IF NOT EXISTS formularios (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  slug TEXT NOT NULL UNIQUE,
  titulo TEXT NOT NULL,
  descripcion TEXT NOT NULL DEFAULT '',
  aviso TEXT NOT NULL DEFAULT '',
  texto_boton TEXT NOT NULL DEFAULT 'Enviar',
  mensaje_final TEXT NOT NULL DEFAULT '',
  campos TEXT NOT NULL DEFAULT '[]',
  acceso TEXT NOT NULL DEFAULT 'libre',
  pin TEXT,
  activo INTEGER NOT NULL DEFAULT 1,
  notificar_email INTEGER NOT NULL DEFAULT 1,
  creado_por TEXT,
  created_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP),
  updated_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP)
);
CREATE INDEX IF NOT EXISTS idx_formularios_created ON formularios(created_at DESC);

CREATE TABLE IF NOT EXISTS formularios_respuestas (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  formulario_id INTEGER NOT NULL,
  datos TEXT NOT NULL DEFAULT '{}',
  estado TEXT NOT NULL DEFAULT 'nueva',
  nota_admin TEXT,
  created_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP),
  updated_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP)
);
CREATE INDEX IF NOT EXISTS idx_formularios_respuestas_form ON formularios_respuestas(formulario_id, created_at DESC);

COMMIT;
